# Start from the standard Ubuntu 18.04 image
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y build-essential

# Install pip
RUN apt-get install -y python3-pip
RUN apt-get install -y libjpeg-dev zlib1g-dev
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir Pillow


# Create and set the working directory
RUN mkdir /code
WORKDIR /code

# Copy the requirements file into the container
COPY requirements.txt /code/

# Install the dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 80